### ISSUE TITLE
Fix to make UI follow scrolling.

### ISSUE THREAD

**Issue by ktrysmt** [ktrysmt/quick-custom-gsearch#20]

**Comment by WellRedPandit** [comment]
fyi. i've replaced  `position: absolute;` with `position: fixed;` in this line https://github.com/ktrysmt/quick-custom-gsearch/blob/master/dist/style.css#L4 and `div.quick-custom-gsearch` is not longer affected by scrolling,.

**Comment by ktrysmt** [comment]
Thank you for the information. I will try and use it. @WellRedPandit

**Comment by ktrysmt** [comment]
I fixed it so that ui would follow scroll. https://github.com/ktrysmt/quick-custom-gsearch/pull/22
Thank you help it.
Please wait the new release.
