### ISSUE TITLE
UI not displayed

### ISSUE THREAD

**Issue by EE5142857** [ktrysmt/quick-custom-gsearch#21]
Windows 10 Pro 64-bit
ChromeVersion 85.0.4183.102 (Official Build) (64-bit)
Site access "On google.com"

![Sep14](https://user-images.githubusercontent.com/44958756/93073236-8cd14c00-f6bd-11ea-80c2-983af14a30ed.jpg)

**Comment by WellRedPandit** [comment]
that's likely because `div#ucs` does not exist anymore. i replaced it with `div#main` in two places
https://github.com/ktrysmt/quick-custom-gsearch/blob/master/src/mainView.js#L13
https://github.com/ktrysmt/quick-custom-gsearch/blob/master/src/parser.js#L5
and the UI started showing again.

**Comment by ktrysmt** [comment]
Thank you create the issue and report it.
I will fix it. @WellRedPandit @EE5142857

**Comment by ktrysmt** [comment]
I fixed an issue with this pull request (https://github.com/ktrysmt/quick-custom-gsearch/pull/22).
Please wait for the new release. Thank you.
